---
title: "StationSim Results."
date: '`r format(Sys.time(), "%d %B, %Y (%H:%M)")`'
output:
  html_document: 
    toc: yes
    pandoc_args: [
      "+RTS", "-K64m", 
      "-RTS"
    ]
fontsize: 10pt
---

# Initialise 

```{r initialise, echo=FALSE, message=FALSE, warning=FALSE}
library(tidyverse)
library(gtools)
library(ggplot2)
library(hexbin) # (this is called automatically if required, but putting it here ensures it has been installed)
library(gridExtra) # For arranging two grids side by side
#library(reshape2) # for melting (taking wide format and making it narrow)


homedir<-"/Users/nick/research_not_syncd/git_projects/keanu-post-hackathon/results/simple"
setwd(homedir)

```

# Load Data

```{r laodData}
# Find files
samples.files <- grep("Results.*.csv", list.files(path = "."), value=TRUE)

if (length(samples.files) != 1) {
  stop("Only work with one results file at a time. Please move any others somewhere else")
}

# Read te file in
samples <- read_csv(samples.files[1], col_names=FALSE)

samples[,ncol(samples)] <- NULL # Last column is NA because I lazily write too many commas

# Truth data are the first entry
truth <- samples[1,]
samples <- samples[-1,]

```

# Plot results

## Spaghetti plot

```{r spag.plot, fig.width=11, fig.height=9}
# Define a fucntion to plot the samples
spag_plot <- function(samples, truth) {

  x_axis <- 1:ncol(samples)
  sample_col <- alpha("#ADD8E6", 0.9)
  truth_col <- "red"

  #create plot
  plot(1, xlim=c(0, max(x_axis)), ylim=c(min(samples), max(samples)), type='l',
       xlab="Number of iterations", ylab = "Number of agents" )
  map(1:nrow(samples), function(x) lines(x_axis, samples[x,], type='l', col=sample_col))
  lines(x_axis, truth, type='l', lwd=2.5, col = truth_col)

  legend("bottomright", c("Samples", "Truth"), lty=c(1,1), lwd=c(2.5,2.5),col=c(sample_col, truth_col))
}


#map2(samples, obIntervals, function(x, obInterval) spag_plot(x, truth, obInterval))
spag_plot(samples, truth)

```

## Density plot

Create the plots

```{r density.plot-create, cache=TRUE}

# Returns a single ggplot2 density plot
density_plot <- function(s, truth) {
  
  # Y values for this sample (num people per iteration)
  y <- t(s[1,])[,1]
  # X values
  x <- 1:length(y)
  # A long two-column matrix will have number of people at every iteration across all samples
  scatter <- cbind(x, y)
  # Now add the rest of the samples
  for (i in 2:nrow(s)) {
    scatter <- rbind(scatter, cbind(1:length(y), t(s[i,])[,1]) )
  }
  scatter <- as.data.frame(scatter)

  the.plot <- ggplot(data=scatter, mapping=aes(x,y)) +
    geom_hex(bins=35, show.legend = FALSE) +
    geom_line(data = data.frame("x"=1:length(truth), "y"=t(truth)), mapping=aes(x,y), colour="red") + # Truth
    #geom_smooth(method="loess", se=TRUE, level=0.95, color="orange") +
    #geom_point(size=0.1, color="white") + # individual points
    ylab("Number of agents in the system")+
    xlab("Iteration")
    #ggtitle(paste("Observation Interval =", obs, sep =' '))
  
  return(the.plot)
}
  
#plots <- map2(samples, obIntervals, function(x, obInterval) density_plot(x, truth, obInterval))
density_plot(samples, truth)

```


